#hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.defer-datasource-initialization = true

spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.type=trace

# Hibernate Dialect ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#postgresql ??
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:mysql://43.203.1.237:3306/lyokyo
spring.datasource.username=root
spring.datasource.password=Tjsdud1103!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.autdoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

#jwt token
spring.profiles.active=dev
jwt.secret=c961e0b1a69f67a8da0801e32e443d949933001fc54e2a3f7263d901426d251c
jwt.expiredMs=3600000 

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#swagger api
springdoc.packages-to-scan=com.travel.japan.controller
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha

#chatgpt api
gpt.model=gpt-3.5-turbo
gpt.api.key=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
gpt.api.url= https://api.openai.com/v1/chat/completions

#?? ?? ??
spring.main.allow-circular-references=true

# ?? ??? ??? ??? ?????.
logging.file.name=/home/ec2-user/logs/application.log
# ?????? ???? ?? ??? DEBUG? ??
# logging.level.com.travel.japan=DEBUG
# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=TRACE



server.address=0.0.0.0

server.port=8080 