spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#hibernate ??
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.defer-datasource-initialization = true

#postgresql??
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/travel
spring.datasource.username=use
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
